export const SIDEBAR_DEFAULT_WIDTH = 250;
export const SIDEBAR_MIN_WIDTH = 170;
export const SIDEBAR_MAX_WIDTH = 500;
export const SIDEBAR_HEADER_HEIGHT = 35;
export const DEFAULT_SIDEBAR_TITLE = 'EXPLORER';